twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_4_horizontal_layout.html.twig'
    globals:
        application_name: '%env(APPLICATION_NAME)%'
        currency: '%env(resolve:DEFAULT_CURRENCY)%'
